# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: py.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08py.proto\x12\x02py\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x07Greeter\x12.\n\x08SayHello\x12\x10.py.HelloRequest\x1a\x0e.py.HelloReply\"\x00\x42\x19Z\x17haowei.ch/go-py-grpc/pyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'py_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027haowei.ch/go-py-grpc/py'
  _HELLOREQUEST._serialized_start=16
  _HELLOREQUEST._serialized_end=44
  _HELLOREPLY._serialized_start=46
  _HELLOREPLY._serialized_end=75
  _GREETER._serialized_start=77
  _GREETER._serialized_end=134
# @@protoc_insertion_point(module_scope)
